#include <Thor/Framework/DataModel/ThBaseTypeFields.h>

namespace Thor
{

THOR_REG_TYPE(ThI64Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThI32Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThI16Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThI8Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThU64Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThU32Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThU16Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThU8Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThF32Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThF64Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThBoolField, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThU16StringField, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThStringField, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThWideStringField, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThVec2Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThVec3Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThVec4Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThVec2dField, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThVec3dField, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThVec4dField, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThMat2x2Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThMat3x3Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThMat4x4Field, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThMat2x2dField, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThMat3x3dField, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThMat4x4dField, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThQuatField, THOR_TYPELIST_1(ThiField));
THOR_REG_TYPE(ThQuatdField, THOR_TYPELIST_1(ThiField));
}