<map version="0.9.0">
<!-- To view this file, download free mind mapping software FreeMind from http://freemind.sourceforge.net -->
<node BACKGROUND_COLOR="#ff0066" CREATED="1286143923595" ID="ID_1020318768" MODIFIED="1286148078248" TEXT="ThField">
<node CREATED="1286143959721" ID="ID_1767318669" MODIFIED="1286144280415" POSITION="right" TEXT="Every field is linked to a corresponding message from the protocol"/>
<node CREATED="1286144042440" ID="ID_1862857425" MODIFIED="1286144091019" POSITION="left" TEXT="Fields can define ports for data driven connections with other fields"/>
<node CREATED="1286148006208" ID="ID_291674847" MODIFIED="1286148031064" POSITION="right" TEXT="Can have multiple commit buffers"/>
<node CREATED="1286148033741" ID="ID_1365296290" MODIFIED="1286148071370" POSITION="left" TEXT="Commits can have a priority value associated"/>
<node CREATED="1286148085042" ID="ID_306125271" MODIFIED="1286148105694" POSITION="right" TEXT="Can have values that are modified using locks"/>
<node CREATED="1286153540863" ID="ID_1494568333" MODIFIED="1286153564192" POSITION="left" TEXT="Field code is generated by the DataForge tool"/>
</node>
</map>
